### ISSUE TITLE
show and animation

### ISSUE THREAD

**Issue by hadrienl** [aurelia/animator-css#54] opened 2016-09-02 10:14 UTC
**I'm submitting a bug report**
- **Library Version:**
  1.0.0
- **Operating System:**
  OSX 10.x
- **Node Version:**
  6.2.0
- **NPM Version:**
  3.8.9
- **JSPM OR Webpack AND Version**
  CLI 1.0.0
- **Browser:**
  Chrome 52
- **Language:**
  ESNext

**Current behavior:**
I have an element with `show.bind` and `au-animate` class. When I toggle element, it doesn't animate correctly.

Here is my template:

```
<div
  show.bind="opened"
  class="dropdown-menu au-animate"
</div>
```

I have first tried with a transition:

```
.dropdown-menu {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 1;

  opacity: 1;
  transition: opacity 2s ease-in;

  &.aurelia-hide-add,
  &.aurelia-hide-remove {
    opacity: 0;
  }
}
```

It didn't works. I can see the `aurelia-hide-remove` apparition when breaking on attribute changes, but it's removed immediately and there is no transition.

Then, I tried with keyframes:

```
.dropdown-menu {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 1;
  opacity: 1;

  &.aurelia-hide-add {
    animation: fadeOut .2s;
  }
  &.aurelia-hide-remove {
    animation: fadeIn .2s;
  }
}

@keyframes fadeIn {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}

@keyframes fadeOut {
  0%   { opacity: 1; }
  100% { opacity: 0; }
}
```

It doesn't really worked. The `aurelia-hide` class come back at the end of the animation and then, `aurelia-hide-add` stays forever like you can see on the following screencast: https://www.dropbox.com/s/w4rwkgyabbcdb6r/aurelia-animation-bug.mov?dl=0

And a demo from a virgin project created with au-cli and latest aurelia-animator-css : https://gist.run/?id=5e8f73adb49480852b8100511429b41f

**Comment by hadrienl** [comment] 2016-09-05 11:56
Btw, no problem with `if` and its `au-(enter|leave)(-active)?`.

**Comment by hadrienl** [comment] 2016-09-13 08:13
https://github.com/aurelia/animator-css/issues/47 fixes animation when using `.2s` delay but with `2s` it fails the same…

**Comment by EisenbergEffect** [comment] 2016-10-03 04:09
@zewa666 Can you look into this?

**Comment by JoshHarris** [comment] 2016-11-29 19:48
We also discovered something like this with a show.bind when the animation ends aurelia-hide comes back. As stated above if.bind works just fine, but we cant use if.bind in this particular situation. Without the animation it works fine.

**Comment by fracz** [comment] 2016-12-14 09:57
+1

**Comment by illiusmedia** [comment] 2017-01-26 09:24
I hade the same problem but only with Firefox.
Made this workaround (instead of the show.bind-attribute):
``<button class="au-animate ${myBool? 'aurelia-hide-add' : ''}">hidden button</button``

**CSS:**
.aurelia-hide-add {
    display: inline !important; /* TODO: Remove this later (firefox hack) */
    -webkit-animation: fadeIn 1s;
    -moz-animation: fadeIn 1s;
    animation: fadeIn 1s;
}

.aurelia-hide-remove {
    -webkit-animation: fadeOut 1s;
    -moz-animation: fadeOut 1s;
    animation: fadeOut 1s;
}

.au-animate {
    /* TODO: Remove this style-block when it's possible to use aurelia-animator-css in Firefox */
    display: none; 
}

@-webkit-keyframes fadeIn {
    0%   { opacity: 0; }
    100% { opacity: 1; }
}

@-webkit-keyframes fadeOut {
    0%   { opacity: 1; }
    100% { opacity: 0; }
}

@-moz-keyframes fadeIn {
    0%   { opacity: 0; }
    100% { opacity: 1; }
}

@-moz-keyframes fadeOut {
    0%   { opacity: 1; }
    100% { opacity: 0; }
}

@keyframes fadeIn {
    0%   { opacity: 0; }
    100% { opacity: 1; }
}

@keyframes fadeOut {
    0%   { opacity: 1; }
    100% { opacity: 0; }
`}

**Comment by icegnome** [comment] 2017-03-01 16:43
I'm still experiencing au-animate not working correctly on show.bind, did this issue just get dropped?

**Comment by nathanchase** [comment] 2017-03-31 00:11
Yeah, I don't see au-animate working on show.bind either - in aurelia-animator-css OR aurelia-animator-velocity.

**Comment by dabide** [comment] 2017-04-05 20:13
I just had a look at the source code: Aurelia searches for the first element in a view having an `au-animate` class. The configured animator implementation is then used: When the element is attached to the DOM, the `enter()` method is called on it, and when it is removed, the `leave()` method is called.

This means that when using `show.bind`, we need to handle the animation ourselves.

The Aurelia documentation is a bit lacking in this area.

**Comment by dabide** [comment] 2017-04-05 20:33
I looked a bit more, and in fact the animator is used by the `show` attribute to add and remove the `aurelia-hide` class. So perhaps I was wrong...

**Comment by jordan-ware** [comment] 2017-09-21 00:11
`view-slot.js` (aurelia-templating) appears to plug into the animator and trigger on leave/entry animations. `if.js` is built on top of `view-slot.js`.

`show.bind` (`show.js`) is a standalone attribute and only adds and removes a custom class to hide the element.

Seems like a simple fix for `show.js` to use the animator - would there be a reason we wouldn't do it this way?

**Comment by jordan-ware** [comment] 2017-09-21 00:31
Ok, so `show.bind` uses the animator `removeClass()` and `addClass()` methods, which take your class and run animations for `{your-class}-add` and `{your-class}-remove`. The `show.bind`  calls this with the aureliaHideClassName constant: `aurelia-hide`.

So in your css you just have to add animations for those classes, e.g.:
```
.aurelia-hide-add {
    animation: fadeOut 0.3s ease-out;
}
.aurelia-hide-remove {
    animation: fadeIn 0.3s ease-out;
}
```

and make sure your element with the binding has au-animate, e.g.:
`<p show.bind="someVMProperty" class="au-animate">animated text</p>`

Tested and it works - hope this helps other people who stumble on this.

**Comment by EisenbergEffect** [comment] 2017-09-21 00:44
@jordan-ware Thanks for being willing to dig into the code and share your findings with the community here. I apologize that this isn't well-documented. I'd love to see if we can improve this. Would anyone on this thread be interested in putting together a markdown file that explains how to use the CSS animation system? We could add that to our official documentation and give the author full credit of course :)

**Comment by jordan-ware** [comment] 2017-09-21 03:05
Seems I was off the mark with this issue - the problem is that classes are getting overlayed when show.bind changes during an animation. I'll have a look - show.bind may just need to manage this concurrent behavior and queue transitions a little better or there may be some change to the animator.

Will report back though I probably won't get time until the weekend.

**Comment by jordan-ware** [comment] 2017-10-22 13:19
Sorry for the delay, my schedules only really just lightened up. I've submitted a PR containing the fix. It appears there was a unit test for this, but it wasn't configured properly and was reporting a false positive.

The addClass/removeClass will now cancel the previous animation and pretty much start from the beginning of the latest animation triggered. I chose this over chaining the animations based on a comment I saw in the aurelia-templating repository about wanting to go in this direction. 

Developers calling the addClass/removeClass methods can chain the promises naturally if they want to.

I'm interested in doing the documentation, I'll see what I can come up with. I'm not sure if I can be too timely with it so if anyone else is interested they may take the point. 😄

**Comment by jordan-ware** [comment] 2017-10-24 03:21
I see the release containing this fix is now available on NPM. 

I've upgraded my project and it has fixed the issue I was experiencing using `show.bind`.

Should be safe to close this now I think.

**Comment by EisenbergEffect** [comment] 2017-10-24 03:27
Thanks!

**Closed by EisenbergEffect** 2017-10-24 03:27 UTC
Labels: bug

**Comment by davidGrocerKey** [comment] 2021-01-11 08:35
This still does not work on Mac,  the '-add' and '-remove' are not being added to the 'aurelia-hide' class. On Windows, it does work
@EisenbergEffect

**Comment by zewa666** [comment] 2021-01-11 09:09
When you say Mac do you mean Safari @davidGrocerKey ?

**Comment by davidGrocerKey** [comment] 2021-01-11 09:18
No,  even on Chrome on Mac

**Comment by zewa666** [comment] 2021-01-11 10:07
Hmm that sounds weird. Perhaps you can share a minimal repro, I need to figure out meanwhile where to get a Mac
